[package]
name = "onebot-message-source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonebot_rs = { version = "0.3.0" ,features = ["matcher"] }
tokio = "1.13.0"